name: 🐞 Fix a bug
description: You fixed it, we love that
title: "BUG: <title>"
labels: [Bug]
body:
  - type: textarea
    attributes:
      description: A concise description the adjustment you made.
      validations:
        required: true
      value: |
        <!-- 
          Thanks for your contribution, we appreciate it!
          
          The first section should explain briefly what was changed.
          Some examples would are always nice to showcase the use.
          The content will be used in the change-logs and release notes
          and addresses developers working with Neos.
          
          If there are issues regarding the topic of your PR link
          them here as `related:` or `resolved`
        -->
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **Flow**: 7.3.4
          - **Neos**: 7.3.3
          - **PHP**: 8.0.18
      value: |
        - Flow:
        - Neos:
        - PHP:
      render: markdown
    validations:
      required: false
