blank_issues_enabled: true
contact_links:
  - name: Neos Discuss
    url: https://discuss.neos.io/
    about: The Neos forum for questions and discussions
  - name: Neos Slack
    url: https://slack.neos.io/
    about: Direct chat between the Neos creators and users